// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dshkvybvimwxrtbqjjfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzaGt2eWJ2aW13eHJ0YnFqamZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTkwNTksImV4cCI6MjA3MzIzNTA1OX0.NTHhO-9JSnEyQzBVriSoBX9dKFuO0YMoN4sd27kH0SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});